# Generated by Django 4.0.2 on 2022-04-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_delete_patient_table_alter_doc_table_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='pat_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('username', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=40)),
                ('confirm_password', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
